### PR TITLE
Update Piaware - Git Pager fix

### PR DESCRIPTION
**Pull request by dschaper**

### CODE REVIEW

**Comment by jprochazka** [comment]
Just a heads up the "version" variable is currently in two places both install.sh which you changed and bash/piaware.sh. I will be consolidating redundant variables as work progresses in the branch named cleanup.

I will test out the change tomorrow morning and merge afterwards.
Thanks for the contribution.

**Comment by jprochazka** [comment]
Actually got around to checking this out tonight.
Ran into a problem.

    Cloning into 'piaware_builder'...
    remote: Counting objects: 115, done.
    remote: Compressing objects: 100% (3/3), done.
    remote: Total 115 (delta 0), reused 0 (delta 0), pack-reused 112
    Receiving objects: 100% (115/115), 27.03 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (65/65), done.
    Checking connectivity... done.
    error: pathspec 'tags/v5c77c4924' did not match any file(s) known to git.

piaware.sh is setup to pull tags not specific commits:

    git checkout tags/v${CURRENTVERSION}

Things were done this way in order to make use of the CURRENTVERSION variable usable not only when cloning a specific tag but also to check if the current version is already installed as well as used to tell the script the correct name of the package to be installed after it has been built.

A way to check if or specify the "CURRENTVERSION" as a commit will need to be added before being able to pull a specific commit from that repository. I hate adding yet another variable and being forced to keep the temporary fix needed due to the fact the 2.1-5-jessie tag kept the same version number as the older 2.1-5 tag but it is looking like this might have to happen...

I am afraid to go back to pulling the master branch being there was issues with work being done there which lead to problems and the addition of the current system.

**Comment by dschaper** [comment]
Well, the current problem that the fix solves seems to be kind of a corner case, and @mutability gave the tip of how to get around it without needing the fix committed. I don't know about future issues that arise in between tags though.

**Comment by jprochazka** [comment]
Why you did not run into any installation errors would be due to the fact the repository would have been cloned and set to the master branch. When trying to change to the nonexistent branch named 'tags/v5c77c4924' in this case git would have reported the error above but installation would have continued on using the master branch.

Honestly it is something that should be trapped somehow by the scripts.
Things such as this will come over time and things mature I'm sure...

Anyways while relocating variables into a single location I went ahead and made the fixes you outlined. as well as fixed the checkout issue. https://github.com/jprochazka/adsb-feeder/issues/48

Once again thanks for pointing out the newer branch containing a needed fix.

**Pull request closed without merging**
